// mockData.js

const mockData = [
    {
        name: 'Mountain Resort A',
        rating: 'A',
        address: '123 Ski Slope Rd, Mountain Town A',
        distance: 45,
        websiteURL: 'https://example.com/resort-a',
        imageSrc: require('../assets/images/3.jpg'),
      },
      {
        name: 'Mountain Resort B',
        rating: 'B',
        address: '456 Ski Slope Rd, Mountain Town B',
        distance: 10,
        websiteURL: 'https://example.com/resort-b',
        imageSrc: require('../assets/images/1.jpg'),
      },
      {
        name: 'Mountain Resort C',
        rating: 'C',
        address: '789 Ski Slope Rd, Mountain Town C',
        distance: 115,
        websiteURL: 'https://example.com/resort-c',
        imageSrc: require('../assets/images/2.jpg'),
      },{
      name: 'Mountain Resort A',
      rating: 'A',
      address: '123 Ski Slope Rd, Mountain Town A',
      distance: 45,
      websiteURL: 'https://example.com/resort-a',
      imageSrc: require('../assets/images/3.jpg'),
    },
    {
      name: 'Mountain Resort B',
      rating: 'B',
      address: '456 Ski Slope Rd, Mountain Town B',
      distance: 10,
      websiteURL: 'https://example.com/resort-b',
      imageSrc: require('../assets/images/1.jpg'),
    },
    {
      name: 'Mountain Resort C',
      rating: 'C',
      address: '789 Ski Slope Rd, Mountain Town C',
      distance: 115,
      websiteURL: 'https://example.com/resort-c',
      imageSrc: require('../assets/images/2.jpg'),
    },
    {
      name: 'Mountain Resort D',
      rating: 'B',
      address: '1011 Ski Slope Rd, Mountain Town D',
      distance: 230,
      websiteURL: 'https://example.com/resort-d',
      imageSrc: require('../assets/images/4.jpg'),
    },
    {
      name: 'Mountain Resort E',
      rating: 'A',
      address: '1213 Ski Slope Rd, Mountain Town E',
      distance: 267,
      websiteURL: 'https://example.com/resort-e',
      imageSrc: require('../assets/images/1.jpg'),
    },
    {
      name: 'Mountain Resort F',
      rating: 'C',
      address: '1415 Ski Slope Rd, Mountain Town F',
      distance: 30,
      websiteURL: 'https://example.com/resort-f',
      imageSrc: require('../assets/images/2.jpg'),
    },
    {
      name: 'Mountain Resort G',
      rating: 'A',
      address: '1617 Ski Slope Rd, Mountain Town G',
      distance: 75,
      websiteURL: 'https://example.com/resort-g',
      imageSrc: require('../assets/images/3.jpg'),
    },
    {
      name: 'Mountain Resort H',
      rating: 'B',
      address: '1819 Ski Slope Rd, Mountain Town H',
      distance: 40,
      websiteURL: 'https://example.com/resort-h',
      imageSrc: require('../assets/images/4.jpg'),
    },
    {
        name: 'Mountain Resort A',
        rating: 'A',
        address: '123 Ski Slope Rd, Mountain Town A',
        distance: 175,
        websiteURL: 'https://example.com/resort-a',
        imageSrc: require('../assets/images/3.jpg'),
      },
      {
        name: 'Mountain Resort B',
        rating: 'B',
        address: '456 Ski Slope Rd, Mountain Town B',
        distance: 100,
        websiteURL: 'https://example.com/resort-b',
        imageSrc: require('../assets/images/1.jpg'),
      },{
        name: 'Mountain Resort A',
        rating: 'A',
        address: '123 Ski Slope Rd, Mountain Town A',
        distance: 45,
        websiteURL: 'https://example.com/resort-a',
        imageSrc: require('../assets/images/3.jpg'),
      },
      {
        name: 'Mountain Resort B',
        rating: 'B',
        address: '456 Ski Slope Rd, Mountain Town B',
        distance: 10,
        websiteURL: 'https://example.com/resort-b',
        imageSrc: require('../assets/images/1.jpg'),
      },
      {
        name: 'Mountain Resort C',
        rating: 'C',
        address: '789 Ski Slope Rd, Mountain Town C',
        distance: 115,
        websiteURL: 'https://example.com/resort-c',
        imageSrc: require('../assets/images/2.jpg'),
      },{
      name: 'Mountain Resort A',
      rating: 'A',
      address: '123 Ski Slope Rd, Mountain Town A',
      distance: 45,
      websiteURL: 'https://example.com/resort-a',
      imageSrc: require('../assets/images/3.jpg'),
    },
    {
      name: 'Mountain Resort B',
      rating: 'B',
      address: '456 Ski Slope Rd, Mountain Town B',
      distance: 10,
      websiteURL: 'https://example.com/resort-b',
      imageSrc: require('../assets/images/1.jpg'),
    },
    {
      name: 'Mountain Resort C',
      rating: 'C',
      address: '789 Ski Slope Rd, Mountain Town C',
      distance: 115,
      websiteURL: 'https://example.com/resort-c',
      imageSrc: require('../assets/images/2.jpg'),
    },
    {
      name: 'Mountain Resort D',
      rating: 'B',
      address: '1011 Ski Slope Rd, Mountain Town D',
      distance: 230,
      websiteURL: 'https://example.com/resort-d',
      imageSrc: require('../assets/images/4.jpg'),
    },
    {
      name: 'Mountain Resort E',
      rating: 'A',
      address: '1213 Ski Slope Rd, Mountain Town E',
      distance: 267,
      websiteURL: 'https://example.com/resort-e',
      imageSrc: require('../assets/images/1.jpg'),
    },
    {
      name: 'Mountain Resort F',
      rating: 'C',
      address: '1415 Ski Slope Rd, Mountain Town F',
      distance: 30,
      websiteURL: 'https://example.com/resort-f',
      imageSrc: require('../assets/images/2.jpg'),
    },
    {
      name: 'Mountain Resort G',
      rating: 'A',
      address: '1617 Ski Slope Rd, Mountain Town G',
      distance: 75,
      websiteURL: 'https://example.com/resort-g',
      imageSrc: require('../assets/images/3.jpg'),
    },
    {
      name: 'Mountain Resort H',
      rating: 'B',
      address: '1819 Ski Slope Rd, Mountain Town H',
      distance: 40,
      websiteURL: 'https://example.com/resort-h',
      imageSrc: require('../assets/images/4.jpg'),
    },
    {
        name: 'Mountain Resort A',
        rating: 'A',
        address: '123 Ski Slope Rd, Mountain Town A',
        distance: 175,
        websiteURL: 'https://example.com/resort-a',
        imageSrc: require('../assets/images/3.jpg'),
      },
      {
        name: 'Mountain Resort B',
        rating: 'B',
        address: '456 Ski Slope Rd, Mountain Town B',
        distance: 100,
        websiteURL: 'https://example.com/resort-b',
        imageSrc: require('../assets/images/1.jpg'),
      }, {
        name: 'Mountain Resort A',
        rating: 'A',
        address: '123 Ski Slope Rd, Mountain Town A',
        distance: 45,
        websiteURL: 'https://example.com/resort-a',
        imageSrc: require('../assets/images/3.jpg'),
      },
      {
        name: 'Mountain Resort B',
        rating: 'B',
        address: '456 Ski Slope Rd, Mountain Town B',
        distance: 10,
        websiteURL: 'https://example.com/resort-b',
        imageSrc: require('../assets/images/1.jpg'),
      },
      {
        name: 'Mountain Resort C',
        rating: 'C',
        address: '789 Ski Slope Rd, Mountain Town C',
        distance: 115,
        websiteURL: 'https://example.com/resort-c',
        imageSrc: require('../assets/images/2.jpg'),
      },{
      name: 'Mountain Resort A',
      rating: 'A',
      address: '123 Ski Slope Rd, Mountain Town A',
      distance: 45,
      websiteURL: 'https://example.com/resort-a',
      imageSrc: require('../assets/images/3.jpg'),
    },
    {
      name: 'Mountain Resort B',
      rating: 'B',
      address: '456 Ski Slope Rd, Mountain Town B',
      distance: 10,
      websiteURL: 'https://example.com/resort-b',
      imageSrc: require('../assets/images/1.jpg'),
    },
    {
      name: 'Mountain Resort C',
      rating: 'C',
      address: '789 Ski Slope Rd, Mountain Town C',
      distance: 115,
      websiteURL: 'https://example.com/resort-c',
      imageSrc: require('../assets/images/2.jpg'),
    },
    {
      name: 'Mountain Resort D',
      rating: 'B',
      address: '1011 Ski Slope Rd, Mountain Town D',
      distance: 230,
      websiteURL: 'https://example.com/resort-d',
      imageSrc: require('../assets/images/4.jpg'),
    },
    {
      name: 'Mountain Resort E',
      rating: 'A',
      address: '1213 Ski Slope Rd, Mountain Town E',
      distance: 267,
      websiteURL: 'https://example.com/resort-e',
      imageSrc: require('../assets/images/1.jpg'),
    },
    {
      name: 'Mountain Resort F',
      rating: 'C',
      address: '1415 Ski Slope Rd, Mountain Town F',
      distance: 30,
      websiteURL: 'https://example.com/resort-f',
      imageSrc: require('../assets/images/2.jpg'),
    },
    {
      name: 'Mountain Resort G',
      rating: 'A',
      address: '1617 Ski Slope Rd, Mountain Town G',
      distance: 75,
      websiteURL: 'https://example.com/resort-g',
      imageSrc: require('../assets/images/3.jpg'),
    },
    {
      name: 'Mountain Resort H',
      rating: 'B',
      address: '1819 Ski Slope Rd, Mountain Town H',
      distance: 40,
      websiteURL: 'https://example.com/resort-h',
      imageSrc: require('../assets/images/4.jpg'),
    },
    {
        name: 'Mountain Resort A',
        rating: 'A',
        address: '123 Ski Slope Rd, Mountain Town A',
        distance: 175,
        websiteURL: 'https://example.com/resort-a',
        imageSrc: require('../assets/images/3.jpg'),
      },
      {
        name: 'Mountain Resort B',
        rating: 'B',
        address: '456 Ski Slope Rd, Mountain Town B',
        distance: 100,
        websiteURL: 'https://example.com/resort-b',
        imageSrc: require('../assets/images/1.jpg'),
      },{
        name: 'Mountain Resort A',
        rating: 'A',
        address: '123 Ski Slope Rd, Mountain Town A',
        distance: 45,
        websiteURL: 'https://example.com/resort-a',
        imageSrc: require('../assets/images/3.jpg'),
      },
      {
        name: 'Mountain Resort B',
        rating: 'B',
        address: '456 Ski Slope Rd, Mountain Town B',
        distance: 10,
        websiteURL: 'https://example.com/resort-b',
        imageSrc: require('../assets/images/1.jpg'),
      },
      {
        name: 'Mountain Resort C',
        rating: 'C',
        address: '789 Ski Slope Rd, Mountain Town C',
        distance: 115,
        websiteURL: 'https://example.com/resort-c',
        imageSrc: require('../assets/images/2.jpg'),
      },{
      name: 'Mountain Resort A',
      rating: 'A',
      address: '123 Ski Slope Rd, Mountain Town A',
      distance: 45,
      websiteURL: 'https://example.com/resort-a',
      imageSrc: require('../assets/images/3.jpg'),
    },
    {
      name: 'Mountain Resort B',
      rating: 'B',
      address: '456 Ski Slope Rd, Mountain Town B',
      distance: 10,
      websiteURL: 'https://example.com/resort-b',
      imageSrc: require('../assets/images/1.jpg'),
    },
    {
      name: 'Mountain Resort C',
      rating: 'C',
      address: '789 Ski Slope Rd, Mountain Town C',
      distance: 115,
      websiteURL: 'https://example.com/resort-c',
      imageSrc: require('../assets/images/2.jpg'),
    },
    {
      name: 'Mountain Resort D',
      rating: 'B',
      address: '1011 Ski Slope Rd, Mountain Town D',
      distance: 230,
      websiteURL: 'https://example.com/resort-d',
      imageSrc: require('../assets/images/4.jpg'),
    },
    {
      name: 'Mountain Resort E',
      rating: 'A',
      address: '1213 Ski Slope Rd, Mountain Town E',
      distance: 267,
      websiteURL: 'https://example.com/resort-e',
      imageSrc: require('../assets/images/1.jpg'),
    },
    {
      name: 'Mountain Resort F',
      rating: 'C',
      address: '1415 Ski Slope Rd, Mountain Town F',
      distance: 30,
      websiteURL: 'https://example.com/resort-f',
      imageSrc: require('../assets/images/2.jpg'),
    },
    {
      name: 'Mountain Resort G',
      rating: 'A',
      address: '1617 Ski Slope Rd, Mountain Town G',
      distance: 75,
      websiteURL: 'https://example.com/resort-g',
      imageSrc: require('../assets/images/3.jpg'),
    },
    {
      name: 'Mountain Resort H',
      rating: 'B',
      address: '1819 Ski Slope Rd, Mountain Town H',
      distance: 40,
      websiteURL: 'https://example.com/resort-h',
      imageSrc: require('../assets/images/4.jpg'),
    },
    {
        name: 'Mountain Resort A',
        rating: 'A',
        address: '123 Ski Slope Rd, Mountain Town A',
        distance: 175,
        websiteURL: 'https://example.com/resort-a',
        imageSrc: require('../assets/images/3.jpg'),
      },
      {
        name: 'Mountain Resort B',
        rating: 'B',
        address: '456 Ski Slope Rd, Mountain Town B',
        distance: 100,
        websiteURL: 'https://example.com/resort-b',
        imageSrc: require('../assets/images/1.jpg'),
      },
  ];
  
  export default mockData;
  